version: '3.8'

services:
  db:
    image: postgres:17
    container_name: farmacia_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: medicamentos
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: farmacia_server
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db 
      - DB_DATABASE=medicamentos
      - DB_PORT=5432
      - PORT=3000
    depends_on:
      - db

  client:
    build: ./client
    container_name: farmacia_client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  postgres_data: